# Generated by Django 5.0.3 on 2024-05-20 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Student_Help', '0005_notificationres'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NotificationRes',
        ),
    ]
