# Generated by Django 5.0.3 on 2024-05-20 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student_Help', '0006_delete_notificationres'),
    ]

    operations = [
        migrations.AddField(
            model_name='logement',
            name='places_disponibles',
            field=models.IntegerField(default=0),
        ),
    ]
